### ISSUE TITLE
App is broken on latest Bokeh + Panel versions

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier-gallery#17]
@pat-schmitt I would be super thankful if you could have a look (not super urgent). The app is now part of teaching activities that @ehultee and I submitted to an open platform.

**Comment by pat-schmitt** [comment]
I am on it. So I could not figure out what the problem is with the current implementation, so I decided now to restructure the great work of @zschirmeister to use more holoviz objects instead of bokeh objects. The good news is that the app is working again in principle. 
However, I thought while I am on it I also try to restructure the text layout using markdown (addressing this issue https://github.com/OGGM/glacier-gallery/issues/16) and there is currently a problem with linking the selected glacier points to the markdown object. I asked about this problem here https://discourse.holoviz.org/t/linking-holoviews-plot-selections-to-panel-markdown-using-js-callbacks/3980.
So I would suggest that I will wait for three weeks or so (depending on how urgent it is) if I am getting useful feedback in discourse, and if not I will make a PR using the old text formatting strategy.
